### ISSUE TITLE
feat: change name 

### ISSUE THREAD

**Issue by 0xMRTT** [AdwCustomizerTeam/AdwCustomizer#128]
### Feature description

@AndroGR asked for committing the name changement 

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/AdwCustomizerTeam/AdwCustomizer/blob/main/CODE_OF_CONDUCT.md).

**Comment by AndroGR** [comment]
I'm gonna make a PR to change the labels and files everywhere. In the meantime, change the team's name and everything I don't have access to.

**Comment by AndroGR** [comment]
Well, not the GitHub links apparently. That's the last one I have to change, so the sooner you do it the better.

**Comment by 0xMRTT** [comment]
Close for now
