### ISSUE TITLE
feat: icon for devel version

### ISSUE THREAD

**Issue by 0xMRTT** [AdwCustomizerTeam/AdwCustomizer#130]
Recently, the devel style was added to the window, we also need a devel icon. 

Nightly/dev version:
![Dev version](https://user-images.githubusercontent.com/8017858/179933141-76c3c4f3-5f34-4fda-9c92-abe5c29f222c.png)

_Originally posted by @ArtyIF in https://github.com/AdwCustomizerTeam/AdwCustomizer/issues/2#issuecomment-1189972863_

**Comment by daudix-UFO** [comment]
Done!
