### ISSUE TITLE
Support for automatic theme generation from wallpaper

### ISSUE THREAD

**Issue by avanishsubbiah** [AdwCustomizerTeam/AdwCustomizer#27]
I created a script [here](https://github.com/avanishsubbiah/adwaita-materialu) that creates a preset.json file with color definitions from any provided image (Created using material-color-utilities).

I was wondering if it would be possible to integrate this functionality into AdwCustomizer as a section in the themes drop down to allow the user to select an automatically generated light or dark theme using their wallpaper. I don't know if it will be entirely possible because I had to write the script in JavaScript because material-color-utils doesn't currently have a Python library yet.

**Comment by daudix-UFO** [comment]
I have done Mockup for this in #25, I really want it too

**Comment by avanishsubbiah** [comment]
I published an npm package for the script [here](https://www.npmjs.com/package/adwaita-materialu) so the script could be integrated by having `main.py` checking if the npm package has been installed, if not run `npm install -g adwaita-materialu`, and then run `gen-materialu-theme -i <Path to image file> -t <Theme type (dark|light)>` to create the auto generated presets.

However, I am not sure if a flatpak can install an npm package within itself.

**Comment by daudix-UFO** [comment]
I am not a developer (for now), but i think we can add this script directly in the project, or like with blueprint-compiler, pull it from git repo

**Comment by ArtyIF** [comment]
I'll probably do it one day. I think it'll be better to rewrite the program so it was more oomox-like for easier integration of new features.

**Comment by avanishsubbiah** [comment]
> I am not a developer (for now), but i think we can add this script directly in the project, or like with blueprint-compiler, pull it from git repo

I looked into some solutions, but there really isn't any good way to get around the dependency of requiring all of NodeJS installed to run the script because the material-color-utilities JavaScript package is only usable with ES6 and pkg only compiles JavaScript packages that use ES5 and below. Some other options like ncc and caxa package it into a single file but still require Node to be installed locally on the system to run it. This is a bit of a problem for it to be usable in flatpak because there isn't a flatpak distribution of NodeJS available, so the user would have to manually install that through their package manager.

I'm currently working on porting material-color-utilities to Python in this [repo](https://github.com/avanishsubbiah/material-color-utilities-python) so this script can be run without Node.

**Comment by daudix-UFO** [comment]
Good luck!

**Comment by avanishsubbiah** [comment]
> Good luck!

Progress went very well. I have ported the whole material-color-utilities library to Python (available [here](https://github.com/avanishsubbiah/material-color-utilities-python)).

It should be very easy now to integrate this into the project. The only dependency it uses is `pillow` because I could not find any other obvious way to iterate through pixels in an image and convert formats without it. Also there is some usage examples of how to generate themes or source colors from images on the repo README.

**Comment by daudix-UFO** [comment]
This is just amazing!

**Comment by 0xMRTT** [comment]
Hi @avanishsubbiah.

Do you want to add this repo to the org, it will be more easy to integrate your amazing tool with Adwaita Manager.

**Comment by avanishsubbiah** [comment]
> Hi @avanishsubbiah.
> 
> Do you want to add this repo to the org, it will be more easy to integrate your amazing tool with Adwaita Manager.

Hello, I'm currently working on updating the code to follow Google's Python guidelines so it can be added into the material-color-utilities repo (pr [here](https://github.com/material-foundation/material-color-utilities/pull/48)). The current code works just fine, it just needs some variables renamed so feel free to fork and use it.

**Comment by 0xMRTT** [comment]
Thanks 👍🙏. I'll include ur generator in the UI redisgn

**Comment by 0xMRTT** [comment]
I'm working on. 

@daudix-UFO: I need to add a combobox for selecting the tone. If the tone is low, the color will be darker, if the tone is high, the color will be lighter 
![Screenshot from 2022-08-11 12-34-52](https://user-images.githubusercontent.com/105598867/184115490-862c0b94-169a-4984-9c92-d8da5a20fbc5.png)
![image](https://user-images.githubusercontent.com/105598867/184115658-f40d85f6-f79b-4dfd-a564-d034a562116a.png)

**Comment by daudix-UFO** [comment]
OK, looks nice! But can you add radio buttons (circles that becomes blue when selected)?

**Comment by daudix-UFO** [comment]
Or segmented slider

**Comment by 0xMRTT** [comment]
I generated palette from this background :

![background_test_monet](https://user-images.githubusercontent.com/105598867/184134864-f2f528af-c663-447e-9687-cee19d8a18fa.png)

With tone = 1:
![Screenshot from 2022-08-11 14-36-36](https://user-images.githubusercontent.com/105598867/184134951-c7f0995c-3626-4f42-9791-ab5ee239c718.png)
With tone=50:
![Screenshot from 2022-08-11 14-37-02](https://user-images.githubusercontent.com/105598867/184135018-45f6a00a-a6b7-4f3c-b01d-01343f2d3aa1.png)
With tone=95
![Screenshot from 2022-08-11 14-37-25](https://user-images.githubusercontent.com/105598867/184135065-6bc159ff-06e5-4d0a-a49d-b8fa5add44b5.png)


I think that i will remove very low tone because it's bad

**Comment by 0xMRTT** [comment]
> OK, looks nice! But can you add radio buttons (circles that becomes blue when selected)?

Where should i add radio buttons ??

**Comment by daudix-UFO** [comment]
> > OK, looks nice! But can you add radio buttons (circles that becomes blue when selected)?
> 
> Where should i add radio buttons ??

Nevermind, just checked, you maked it correctly

**Comment by daudix-UFO** [comment]
I think tones works pretty good, but first one is too dark

**Comment by 0xMRTT** [comment]
Yes, i am removing tone 1. I need to try all others tone to determine which one is better and set this one as default

**Comment by avanishsubbiah** [comment]
> I generated palette from this background :
> 
> ![background_test_monet](https://user-images.githubusercontent.com/105598867/184134864-f2f528af-c663-447e-9687-cee19d8a18fa.png)
> 
> With tone = 1: ![Screenshot from 2022-08-11 14-36-36](https://user-images.githubusercontent.com/105598867/184134951-c7f0995c-3626-4f42-9791-ab5ee239c718.png) With tone=50: ![Screenshot from 2022-08-11 14-37-02](https://user-images.githubusercontent.com/105598867/184135018-45f6a00a-a6b7-4f3c-b01d-01343f2d3aa1.png) With tone=95 ![Screenshot from 2022-08-11 14-37-25](https://user-images.githubusercontent.com/105598867/184135065-6bc159ff-06e5-4d0a-a49d-b8fa5add44b5.png)
> 
> I think that i will remove very low tone because it's bad

There is some extra processing used beyond the palette to make a cohesive scheme with Material You. I recommend picking tokens from here: https://m3.material.io/styles/color/the-color-system/tokens, and there might be a way to have it brighten the tone of the generated tokens for tone selection.

As an example [here](https://github.com/avanishsubbiah/material-you-theme/blob/main/material-you-theme%40asubbiah.com/color_mappings.js) are some token to adwaita mappings.

**Comment by 0xMRTT** [comment]
@daudix-UFO I also need to add another combo box to select if the theme will be light or dark

**Comment by daudix-UFO** [comment]
> @daudix-UFO I also need to add another combo box to select if the theme will be light or dark

I think we need to make automatic, see #12

**Comment by 0xMRTT** [comment]
Yes, but we can also let user choice

**Comment by daudix-UFO** [comment]
> Yes, but we can also let user choice

Also correct!

**Comment by 0xMRTT** [comment]
It's work....

**Comment by 0xMRTT** [comment]
Also added automatic choice

**Comment by daudix-UFO** [comment]
Also, maybe wiered question, but any idea why there is a _huge_ difference in performance between material you GNOME extension and in-app generator?

**Comment by 0xMRTT** [comment]
Material you is written in JavaScript with the original library by google. Adwaita Manager use a port in python. Just created 14 days ago

**Comment by 0xMRTT** [comment]
It's a goal for the next release

**Comment by avanishsubbiah** [comment]
> Also, maybe wiered question, but any idea why there is a _huge_ difference in performance between material you GNOME extension and in-app generator?

By default the extension resizes the wallpaper to 64x64 before processing it because it barely makes any visible difference to the colors picked. Also the Python port I made is slower than the JavaScript version of the material-color-utilities library. Either of these or both could contribute to performance differences.

**Comment by daudix-UFO** [comment]
Thank you for detailed explanation!

**Comment by 0xMRTT** [comment]
#108 will improve performance
