### ISSUE TITLE
Running fails with error code 139 (issue with PyGObject)

### ISSUE THREAD

**Issue by AndroGR** [AdwCustomizerTeam/AdwCustomizer#70]
# Issue
I just installed the application and I cannot run it. Running:
```sh
$ flatpak run com.github.ArtyIF.AdwCustomizer
```
returns 139, no error messages or anything else. What is wrong?

**Comment by AndroGR** [comment]
Issue #69 seems to be the exact same thing. It looks like it isn't a problem of the application directly, so I will dig down to the problem and make a pull request, hopefully.

**Comment by EntityinArray** [comment]
My error is exactly the same as yours, probably a bug in pygobject. Interesting thing is that AdwCustomizer worked absolutely fine and then suddenly stopped working, there is probably some state that causes pygobject to cause a segfault

**Comment by ArtyIF** [comment]
I am getting the same error too now, actually. There's a chance it's 
one of the commits that did something.

**Comment by ArtyIF** [comment]
Nevermind, it does seem to be an issue with PyGObject. I created a new project, and when I built it with flatpak-builder it still had the same error.

**Comment by EntityinArray** [comment]
Created an issue:
https://gitlab.gnome.org/GNOME/pygobject/-/issues/538

**Comment by AndroGR** [comment]
Perhaps until the issue is resolved some older version of the library should be used to make sure it works for everyone.

**Comment by daudix-UFO** [comment]
maybe reason is update of GNOME SDK's?

**Comment by daudix-UFO** [comment]
I just builded latest version, and updated GNOME Platform (Nightly), and app works again!

![изображение](https://user-images.githubusercontent.com/77155297/183643812-477917a0-32c8-4807-ac8c-245ef8e3510b.png)

**Comment by daudix-UFO** [comment]
I close this issue for now, if problem will go back, we will reopen it

**Comment by AndroGR** [comment]
Indeed fixed, I can verify.

**Comment by EntityinArray** [comment]
Fixed for me as well!
