### ISSUE TITLE
Icon for AdwCustomizerTeam

### ISSUE THREAD

**Issue by daudix-UFO** [AdwCustomizerTeam/AdwCustomizer#73]
Not best, but also not awful

![logo](https://user-images.githubusercontent.com/77155297/183549314-06dd425e-ce88-4555-8689-e843cd2cf02a.png)

[📎 AdwCustomizerTeam.zip](https://github.com/AdwCustomizerTeam/AdwCustomizer/files/9286236/AdwCustomizerTeam.zip)

**Comment by AndroGR** [comment]
While it is beautiful, it doesn't really match the Adwaita design. And considering that this application is explicitly designed *for* Adwaita, that could be a problem for some.

**Comment by 0xMRTT** [comment]
Maybe something like the AdwaitaCustomizer icon ?

**Comment by daudix-UFO** [comment]
> While it is beautiful, it doesn't really match the Adwaita design. And considering that this application is explicitly designed _for_ Adwaita, that could be a problem for some.

Yes, it's not regular app icon design, but instead, GNOME projects icon design, for example, libadwaita have this project icon

![изображение](https://user-images.githubusercontent.com/77155297/183633043-854c2e23-fde2-4b3b-a831-4b63fd049ec1.png)

**Comment by 0xMRTT** [comment]
Yes, it's not important if the icon of the team doesn't match gnome hig because it's not the icon of the project. It's the icon of the team behind the project.

**Comment by daudix-UFO** [comment]
Have made some more HIG versions, but I think it look quite wrong compared to all GitLab emblems

![logo-alt](https://user-images.githubusercontent.com/77155297/183766730-c114781a-d548-4f1a-9719-2981d10da855.png)

![logo-alt-dark](https://user-images.githubusercontent.com/77155297/183766734-a98e71dc-2e56-4a03-b6cf-c9c2e132cea8.png)

**Comment by daudix-UFO** [comment]
![image](https://user-images.githubusercontent.com/77155297/183767092-7a83d20f-9a7d-474a-98be-c66abce447c9.png)

![image](https://user-images.githubusercontent.com/77155297/183767139-dfd90ad4-c431-4f90-995e-5e09e75eda81.png)

![image](https://user-images.githubusercontent.com/77155297/183767167-18c6d29f-fb22-4a24-ab78-9aac5e4132c4.png)

**Comment by 0xMRTT** [comment]
Keep the first one. Ask @ArtyIF for changing the org icon

**Comment by ArtyIF** [comment]
You gotta make it smaller. In some places apparently it's displayed as a circle, and the logo doesn't fit in one.

![image](https://user-images.githubusercontent.com/8017858/183828062-cc42d0cb-5d5c-420b-bebf-e2d7134067b4.png)

**Comment by 0xMRTT** [comment]
Otherwise you can use the first logo which will be perfect in a circle

**Comment by daudix-UFO** [comment]
Smaller version

![logo-alt-small](https://user-images.githubusercontent.com/77155297/183846604-04a8d1ce-4b09-43f0-b0e8-f325d2cf935f.png)

[png](https://user-images.githubusercontent.com/77155297/183846604-04a8d1ce-4b09-43f0-b0e8-f325d2cf935f.png)
[svg](https://user-images.githubusercontent.com/77155297/183846610-6914c223-6e85-40ac-b7c6-71bf8c7b0bec.svg)

**Comment by daudix-UFO** [comment]
By the way, first one generated using GNOME Design app - [Emblems](https://gitlab.gnome.org/World/design/emblem)
