### ISSUE TITLE
feat: add code of conduct 

### ISSUE THREAD

**Issue by 0xMRTT** [AdwCustomizerTeam/AdwCustomizer#79]
### Feature description

recently, I've added issue template and in templates you need to agree with code of conduct. So, we need a code of conduct 

### Self-service

- [X] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/AdwCustomizerTeam/community/blob/main/CONTRIBUTING_GUIDELINES.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/AdwCustomizerTeam/community/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment]
Here are some templates:

https://gitlab.gnome.org/federico/gnome-code-of-conduct/

https://github.com/sagesharp/code-of-conduct-template/

**Comment by 0xMRTT** [comment]
I can use the GitHub one

**Comment by 0xMRTT** [comment]
But what contact method should I add ?

I mean people or team to contact for reporting an issue

**Comment by daudix-UFO** [comment]
> I can use the GitHub one

Oh, I don't knew that there is GitHub one :/

**Comment by 0xMRTT** [comment]
Go to insights > community standards > code of conduct

**Comment by daudix-UFO** [comment]
> But what contact method should I add ?
> 
> I mean people or team to contact for reporting an issue

I think special matrix group is pretty good place, but because not everyone have matrix, we can make a discussion only for issues

**Comment by 0xMRTT** [comment]
Created a report category in gh discussions

**Comment by daudix-UFO** [comment]
Also, what description we can put to this category?

**Comment by 0xMRTT** [comment]
Ask or report an issue about the community

**Comment by 0xMRTT** [comment]
Maybe ?

**Comment by daudix-UFO** [comment]
Sounds good
