### ISSUE TITLE
bug: "Reset Applied Color Scheme" not working

### ISSUE THREAD

**Issue by daudix-UFO** [AdwCustomizerTeam/AdwCustomizer#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Clicking on "Reset Applied Color Scheme" notthing happens, launching from terminal don't give any info

### To Reproduce

1. Open Adwaita Manager
2. Apply preset
3. Click on "Reset Applied Color Scheme" in hamburger menu

### Expected behavior

Reset all CSS to default ones

### Screenshots

![Снимок экрана от 2022-08-10 20-13-35](https://user-images.githubusercontent.com/77155297/183975348-fa0f5401-7a90-4856-9a0f-a5a1991087f0.png)
![Снимок экрана от 2022-08-10 20-13-42](https://user-images.githubusercontent.com/77155297/183975353-c6f8c0b5-d158-488f-984c-d35b71416ea3.png)
![Снимок экрана от 2022-08-10 20-14-01](https://user-images.githubusercontent.com/77155297/183975361-96130806-3a4d-4e90-9e24-fc6636dea5a4.png)

### OS

Fedora Linux 36 (Silverblue edition)

### Version

Latest manual build

### Installation method

Other

### Additional context

I have restarted apps and system

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
On which branch ? next or main ?

**Comment by daudix-UFO** [comment]
main

**Comment by 0xMRTT** [comment]
There is the same problem on `next`

**Comment by 0xMRTT** [comment]
Corrected in next
